name: Build Docker Image
run-name: Building image
on:
  workflow_call:
    inputs:
      IMAGE:
        required: true
        type: string
      TAG:
        required: true
        type: string
      BUILD_PATH:
        required: true
        type: string
      DOCKER_ACR:
        required: true
        type: string
      HASH_SUFFIX:
        required: false
        default: true
        type: boolean
    secrets:
      DOCKER_TOKEN:
        required: true
        description: A token to authenticate against DOCKER_ACR

jobs:
  build:
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set Tag for dev branches with commit hash
        if: github.ref != 'refs/heads/main' && inputs.HASH_SUFFIX
        run: |
          echo "TAG=${{ inputs.TAG }}-${GITHUB_SHA::6}" >> ${GITHUB_ENV}

      - name: Set Tag for dev branches
        if: github.ref != 'refs/heads/main' && !inputs.HASH_SUFFIX
        run: |
          echo "TAG=${{ inputs.TAG }}-dev" >> ${GITHUB_ENV}

      # Need to get an ACR where to push the image
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.DOCKER_ACR }}
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: set lower case owner name
        run: |
          echo "OWNER_LC=${OWNER,,}" >> ${GITHUB_ENV}
        env:
          OWNER: '${{ github.repository_owner }}'
      - name: Build and push ${{ inputs.IMAGE }} image
        uses: docker/build-push-action@v5
        with:
          context: ${{ inputs.BUILD_PATH }}
          file: ${{ inputs.BUILD_PATH }}/Dockerfile
          tags: ${{ inputs.DOCKER_ACR }}/${{ env.OWNER_LC }}/${{ inputs.IMAGE }}:${{ inputs.TAG }}
          push: true
