name: Build Docker Image
run-name: Building image
on:
  workflow_call:
    inputs:
      HELM_REPO:
        required: true
        type: string
      USER_HELM:
        required: true
        type: string
      VERSION:
        required: true
        type: string
      CHART_NAME:
        required: true
        type: string
      PATH_BUILD:
        required: true
        type: string
      PATH_CHART:
        required: false
        type: string
        default: ../../artifacts/
    secrets:
      HELM_TOKEN:
        required: true
        description: A token to authenticate against the Helm Repository
env:
  HELM_CHANNEL: stable

jobs:
    helm:
      runs-on: ubuntu-latest
      permissions:
        contents: write
      steps:
      - uses: actions/checkout@v4
      - name: Build helm archive
        working-directory: ${{ inputs.PATH_BUILD }}
        run: |
            helm package . -d ${{ inputs.PATH_CHART }} --version ${{ inputs.VERSION }}

      - name: Set helm channel to develop for dev branches
        if: github.ref != 'refs/heads/main'
        run: echo "HELM_CHANNEL=develop" >> ${GITHUB_ENV}

      - name: Push to GitHub pages
        run: |
          git fetch
          git checkout gh-pages
          mv artifacts/${{ inputs.CHART_NAME }}-${{ inputs.VERSION }}.tgz docs/
          helm repo index fn-task-controller --url https://aridhia-open-source.github.io/federated-node-task-controller
          git add docs/
          git commit -m "Version ${{ inputs.VERSION }}"
          git push

      - name: Publish Release
        uses: ncipollo/release-action@v1
        with:
            artifacts: "artifacts/${{ inputs.CHART_NAME }}-${{ inputs.VERSION }}.tgz"
            tag: ${{ inputs.VERSION }}
            skipIfReleaseExists: true
