name: Build Docker Image
run-name: Building image
on:
  workflow_call:
    inputs:
      VERSION:
        required: true
        type: string
      APP_VERSION:
        required: true
        type: string
      CHART_NAME:
        required: true
        type: string
      PATH_BUILD:
        required: true
        type: string
      PATH_CHART:
        required: false
        type: string
        default: ../../artifacts/
      PAGES_BRANCH:
        required: false
        type: string
        default: gh-pages
      PAGES_BRANCH_PATH:
        required: false
        type: string
        default: docs
      IS_TAG:
        required: false
        type: string
        default: 'false'
    secrets:
      HELM_TOKEN:
        required: true
        description: A token to authenticate against the Helm Repository

jobs:
    helm:
      runs-on: ubuntu-latest
      permissions:
        contents: write
      steps:
      - uses: actions/checkout@v4
      - name: Build helm archive
        working-directory: ${{ inputs.PATH_BUILD }}
        run: |
            helm package . -d ${{ inputs.PATH_CHART }} --version ${{ inputs.VERSION }} --app-version ${{ inputs.APP_VERSION }}

      - name: Push to GitHub pages
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git fetch
          git checkout ${{ inputs.PAGES_BRANCH }}
          mv artifacts/${{ inputs.CHART_NAME }}-${{ inputs.VERSION }}.tgz ${{ inputs.PAGES_BRANCH_PATH }}/

          helm repo index ${{ inputs.PAGES_BRANCH_PATH }}
          git add ${{ inputs.PAGES_BRANCH_PATH }}
          git commit -m "Version ${{ inputs.VERSION }}"
          git push

      - name: Publish Release
        uses: ncipollo/release-action@v1
        with:
            artifacts: "artifacts/${{ inputs.CHART_NAME }}-${{ inputs.VERSION }}.tgz"
            tag: ${{ inputs.VERSION }}
            skipIfReleaseExists: true
            makeLatest: ${{ inputs.IS_TAG == 'true'}}
