name: Build Docker Image
run-name: Building image
on:
  workflow_call:
    inputs:
      VERSION:
        required: true
        type: string
      APP_VERSION:
        required: true
        type: string
      CHART_NAME:
        required: true
        type: string
      PATH_BUILD:
        required: true
        type: string
      PATH_CHART:
        required: false
        type: string
        default: artifacts
      PAGES_BRANCH:
        required: false
        type: string
        default: gh-pages
      PAGES_BRANCH_PATH:
        required: false
        type: string
        default: docs
      IS_TAG:
        required: false
        type: string
        default: 'false'
      RELEASE_NOTES:
        required: false
        type: string
        default: ''
      HAS_SUBCHART:
        required: false
        type: boolean
        default: false

jobs:
    helm:
      runs-on: ubuntu-latest
      permissions:
        contents: write
      steps:
      - uses: actions/checkout@v4
      - name: Refresh dependencies
        if: inputs.HAS_SUBCHART
        working-directory: ${{ inputs.PATH_BUILD }}
        run: |
            helm dependency build || helm dependency update
      - name: Build helm archive
        working-directory: ${{ inputs.PATH_BUILD }}
        run: |
            helm package . -d ${{ github.workspace }}/${{ inputs.PATH_CHART }} --version ${{ inputs.VERSION }} --app-version ${{ inputs.APP_VERSION }}

      - name: Push to GitHub pages
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git fetch
          git checkout ${{ inputs.PAGES_BRANCH }}
          mv ${{ github.workspace }}/${{ inputs.PATH_CHART }}/${{ inputs.CHART_NAME }}-${{ inputs.VERSION }}.tgz ${{ inputs.PAGES_BRANCH_PATH }}/

          helm repo index ${{ inputs.PAGES_BRANCH_PATH }}
          git add ${{ inputs.PAGES_BRANCH_PATH }}
          git commit -m "Version ${{ inputs.VERSION }}"
          git push

      - name: Create Release Notes file
        if: inputs.IS_TAG == 'true'
        run: |
          touch ReleaseNotes.md
          if [[ -f CHANGELOG.md ]]; then
            python -c "import re; f=open('CHANGELOG.md'); print(re.findall(r'##\s\d+\.\d+\.\d+\n[^#]+', '\n'.join(f.readlines()))[0].strip())" > ReleaseNotes.md
          fi
          cat ReleaseNotes.md

      - name: Publish Release
        uses: ncipollo/release-action@v1
        if: inputs.IS_TAG == 'true'
        with:
            artifacts: "${{ inputs.PAGES_BRANCH_PATH }}/${{ inputs.CHART_NAME }}-${{ inputs.VERSION }}.tgz"
            tag: ${{ inputs.VERSION }}
            skipIfReleaseExists: true
            makeLatest: true
            bodyFile: ReleaseNotes.md
