name: Update Task
run-name: update_task
on:
  workflow_call:
    inputs:
      DEST_BRANCH:
        required: true
        type: string
      TEMPLATE_PATH:
        required: true
        type: string
    secrets:
      SA_TOKEN:
        required: true
        description: A service account token used to access the codebase

env:
  GH_TOKEN: ${{ secrets.SA_TOKEN }}

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Save template
        id: save-template
        run: |
          TEMPL=$(cat ${{ inputs.TEMPLATE_PATH }} | jq -c)
          echo "TEMPL_CONTENTS=${TEMPL}" >> "$GITHUB_OUTPUT"

      - name: Checkout Argo Branch
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.DEST_BRANCH }}
          token: ${{ env.GH_TOKEN }}
      - name: Update values
        env:
          TEMPL_CONTENTS: ${{ steps.save-template.outputs.TEMPL_CONTENTS }}
        run: |
          AUTHOR=$(gh pr list -B pipe-test --state merged --json author,mergedAt,mergedBy,headRefName,number | jq '.[0].author.login')
          if [[ "$AUTHOR" == 'null' ]]; then
            echo "No user found"
            exit 1
          fi
          git config --global user.name 'BotMan'
          git config --global user.email 'r-casula@users.noreply.github.com'

          echo "$TEMPL_CONTENTS" | jq ".spec |= .+ {\"user\": {\"username\": $AUTHOR}, \"repository\": \"${{ github.repository }}\", \"organization\": \"${{ github.repository_owner }}\"}" > ${{ inputs.TEMPLATE_PATH }}
          git add ${{ inputs.TEMPLATE_PATH }}
          git commit -am "Added user info"
          git push
