name: Version bump
run-name: Version bump
on:
  workflow_call:
    inputs:
      chartVersion:
        description: 'New Helm Chart version'
        required: true
        type: string
      appVersion:
        description: 'New tag the docker images are going to use'
        required: false
        type: string
      dryRun:
        description: 'Dry run, no changes committed. Shows the new Chart.yaml contents'
        required: false
        type: boolean
        default: true
      chartDir:
        description: Path where the helm chart is located
        required: true
        type: string

permissions:
  contents: write

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - name: Update Version
        working-directory: ${{ inputs.chartDir }}
        env:
          CHART_VERSION: ${{ inputs.chartVersion }}
          APP_VERSION: ${{ inputs.appVersion }}
        run: |
          if [[ ! $(grep '${CHART_VERSION}' Chart.yaml) ]]; then
            echo "Nothing to change. Exiting early"
            exit 0
          fi
          sed -i "s/version: .*/version: ${CHART_VERSION}/" Chart.yaml

          if [[ -n "${APP_VERSION}" ]]; then
            sed -i "s/version: .*/appVersion: \"${APP_VERSION}\"/" Chart.yaml
          fi

          cat Chart.yaml

          if [[ "${{ inputs.dryRun }}" == "false" ]]; then
            git config user.email "phemsbot@phems.com"
            git config user.name "PHEMS bot"

            git add Chart.yaml
            git commit -m "Version bump to ${CHART_VERSION}"
            git push
          fi
